apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: secret-docker
  namespace: tekton-maven-sample2
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
  labels:
    serviceAccount: tekton-mvn-sa
data:
  password: dGVzdA==
  username: dGVzdA==
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: secret-git
  namespace: tekton-maven-sample2
  annotations:
    tekton.dev/git-0: https://github.ibm.com
  labels:
    serviceAccount: tekton-mvn-sa
data:
  password: dGVzdA==
  username: dGVzdA==