apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-mvn-sa
  namespace: tekton-maven-sample2
secrets:
  - name: secret-docker
  - name: secret-git
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-cart-role-binding
  namespace: tekton-maven-sample2
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tekton-mvn-sa
  