apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-mvn
  namespace: tekton-maven-sample2
spec:
  workspaces:
    - name: maven-repo
  inputs:
    params:
      - name: GOALS
        description: The Maven goals to run
        default: "package"
    resources:
      - name: source
        type: git
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Goals -> ${inputs.params.GOALS}"
    - name: echo2
      image: ubuntu
      command:
        - /bin/bash
      args:
        - '-c'
        - >
          set -e
          echo "Goals --> ${inputs.params.GOALS}"
    - name: mvn
      image: maven:3.6.3-openjdk-14
      imagePullPolicy: IfNotPresent
      command:
        - /usr/bin/mvn
      args:
        # - -Dmaven.repo.local=${workspaces.maven-repo.path}
        - ${inputs.params.GOALS}
      workingDir: /workspace/source
